CREATE TABLE [dbo].[ACTIVITIES]
(
	ACTIVITY_ID INT NOT NULL IDENTITY (1,1),
	ACTIVITY_TYPE_ID TINYINT NOT NULL,
	MEMBER_ID INT NOT NULL,
	MONEY_SPENT SMALLMONEY NULL,
	MONEY_EARNED SMALLMONEY NULL,
	ACTIVITY_START_DATE DATE,
	ACTIVITY_END_DATE DATE

	CONSTRAINT [pk_ACTIVITIES_ACTIVITY_ID] PRIMARY KEY CLUSTERED (ACTIVITY_ID)
);
GO

ALTER TABLE dbo.ACTIVITIES
WITH CHECK ADD CONSTRAINT [fk_ACTIVITIES_to_ACTIVITY_TYPES_ACTIVITY_TYPE_ID] FOREIGN KEY (ACTIVITY_TYPE_ID)
REFERENCES dbo.ACTIVITY_TYPES (ACTIVITY_TYPE_ID);
GO

ALTER TABLE dbo.ACTIVITIES
WITH CHECK ADD CONSTRAINT [fk_ACTIVITIES_to_MEMBERSHSIP] FOREIGN KEY (MEMBER_ID)
REFERENCES dbo.MEMBERSHIP (MEMBER_ID);
GO