CREATE TABLE [dbo].[TRANSACTION_TYPES]
(
	TRANSACTION_TYPE_ID TINYINT NOT NULL,
	[DESCRIPTION] VARCHAR(80) NOT NULL

	CONSTRAINT [pk_TRANSACTION_TYPES_TRANSACTION_TYPE_ID] PRIMARY KEY CLUSTERED (TRANSACTION_TYPE_ID)
);
GO