CREATE TABLE [dbo].[CONTACT_METHODS]
(
	CONTACT_METHOD_ID TINYINT NOT NULL,
	[DESCRIPTION] VARCHAR(80) NOT NULL,

	CONSTRAINT [pk_CONTACT_METHODS_CONTACT_METHOD_ID] PRIMARY KEY CLUSTERED (CONTACT_METHOD_ID)
);

