CREATE TABLE [dbo].[CONTACT_INFO]
(
	MEMBER_ID INT NOT NULL,
	CONTACT_METHOD_ID TINYINT,
	CONTACT_INFO VARCHAR(255) NOT NULL,

	CONSTRAINT [pk_CONTACT_INFO_MEMBER_ID_CONTACT_METHOD_ID] PRIMARY KEY CLUSTERED (MEMBER_ID, CONTACT_METHOD_ID)
);
GO

ALTER TABLE dbo.CONTACT_INFO
WITH CHECK ADD CONSTRAINT [fk_CONTACT_INFO_to_MEMBERSHIP_MEMBER_ID] FOREIGN KEY (MEMBER_ID)
REFERENCES dbo.MEMBERSHIP (MEMBER_ID);
GO

ALTER TABLE dbo.CONTACT_INFO
WITH CHECK ADD	CONSTRAINT [fk_CONTACT_INFO_to_CONTACT_METHODS_CONTACT_METHOD_ID] FOREIGN KEY (CONTACT_METHOD_ID)
REFERENCES dbo.CONTACT_METHODS (CONTACT_METHOD_ID);
GO
