CREATE TABLE [dbo].[MEMBERSHIP_TYPES]
(
	MEMBERSHIP_TYPE_ID TINYINT NOT NULL,
	[DESCRIPTION] VARCHAR(80) NOT NULL,

	CONSTRAINT [pk_MEMBERSHIP_TYPES_MEMBERSHIP_TYPE_ID] PRIMARY KEY CLUSTERED (MEMBERSHIP_TYPE_ID)
);
