CREATE TABLE [dbo].[MEMBERSHIP_STATUS]
(
	MEMBERSHIP_STATUS_ID TINYINT NOT NULL,
	[DESCRIPTION] VARCHAR(80) NOT NULL,

	CONSTRAINT [pk_MEMBERSHIP_STATUS_MEMBERSHIP_TYPE_ID] PRIMARY KEY CLUSTERED (MEMBERSHIP_STATUS_ID)
);
