CREATE TRIGGER UPDATE_LAST_MODIFIED_IN_MEMBERSHIP
	ON dbo.MEMBERSHIP
	FOR UPDATE
	AS
	BEGIN
		SET NOCOUNT ON;

		UPDATE M
		SET M.LAST_MODIFIED_DATE = GETDATE()

		FROM dbo.MEMBERSHIP M
		WHERE EXISTS (SELECT 1 FROM Deleted D WHERE D.MEMBER_ID = M.MEMBER_ID);

	END;
