//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchResourceManagerWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChurchResourceDbEntities : DbContext
    {
        public ChurchResourceDbEntities()
            : base("name=ChurchResourceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITy> ACTIVITIES { get; set; }
        public virtual DbSet<ACTIVITY_TYPES> ACTIVITY_TYPES { get; set; }
        public virtual DbSet<CONTACT_INFO> CONTACT_INFO { get; set; }
        public virtual DbSet<CONTACT_METHODS> CONTACT_METHODS { get; set; }
        public virtual DbSet<FAMILy> FAMILIES { get; set; }
        public virtual DbSet<LOCATION> LOCATIONS { get; set; }
        public virtual DbSet<MARITAL_STATUS> MARITAL_STATUS { get; set; }
        public virtual DbSet<MEMBER_GROUPS> MEMBER_GROUPS { get; set; }
        public virtual DbSet<MEMBERSHIP> MEMBERSHIPs { get; set; }
        public virtual DbSet<MEMBERSHIP_TYPES> MEMBERSHIP_TYPES { get; set; }
    }
}
