//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchResourceManagerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_INFO
    {
        public int MEMBER_ID { get; set; }
        public byte CONTACT_METHOD_ID { get; set; }
        public string CONTACT_INFO1 { get; set; }
    
        public virtual CONTACT_METHODS CONTACT_METHODS { get; set; }
        public virtual MEMBERSHIP MEMBERSHIP { get; set; }
    }
}
