//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchResourceManagerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSHIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBERSHIP()
        {
            this.ACTIVITIES = new HashSet<ACTIVITIES>();
            this.CONTACT_INFO = new HashSet<CONTACT_INFO>();
            this.TITHES = new HashSet<TITHES>();
            this.DONATIONS = new HashSet<DONATIONS>();
        }
    
        public Nullable<int> FAMILY_ID { get; set; }
        public int MEMBER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GENDER { get; set; }
        public Nullable<short> LOCATION_ID { get; set; }
        public Nullable<byte> MARITAL_STATUS_ID { get; set; }
        public Nullable<byte> GROUP_ID { get; set; }
        public Nullable<byte> PREFERRERD_CONTACT_METHOD { get; set; }
        public Nullable<System.DateTime> EXIT_DATE { get; set; }
        public System.DateTime LAST_MODIFIED_DATE { get; set; }
        public Nullable<byte> RELATIONSHIP_TYPE_ID { get; set; }
        public Nullable<byte> MEMBERSHIP_STATUS_ID { get; set; }
        public System.DateTime EFFECTIVE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITIES> ACTIVITIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACT_INFO> CONTACT_INFO { get; set; }
        public virtual FAMILIES FAMILIES { get; set; }
        public virtual LOCATIONS LOCATIONS { get; set; }
        public virtual MARITAL_STATUS MARITAL_STATUS { get; set; }
        public virtual MEMBER_GROUPS MEMBER_GROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TITHES> TITHES { get; set; }
        public virtual MEMBERSHIP_STATUS MEMBERSHIP_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONATIONS> DONATIONS { get; set; }
    }
}
