//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchResourceManagerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFERINGS
    {
        public int OFFERING_ID { get; set; }
        public System.DateTime OFFERING_DATE { get; set; }
        public byte DONATION_TYPE_ID { get; set; }
        public decimal OFFERING_AMOUNT { get; set; }
        public string COMMENTS { get; set; }
    }
}
